# Starter pipeline
resources:
  repositories:
  - repository: adfrepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: adf_test
    ref: adf_publish
    name: lakime/adfautogd

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: adfrepo
- script: dir $(Build.SourcesDirectory)/greendtest1/
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'BDAG'
    subscriptionId: '64e274c3-3493-4116-90f8-9c3098aaa268'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'greendtest'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/greendtest1/ARMTemplateForFactory.json'
    csmParametersFile: '$(Build.SourcesDirectory)/greendtest1/ARMTemplateParametersForFactory.json'

    overrideParameters: '-abc supertest'
    deploymentMode: 'Incremental'


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
